default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>

development:
  <<: *default
  database: document_storage_mvp_development

test:
  <<: *default
  database: document_storage_mvp_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    prepared_statements: false
  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate
